### ISSUE TITLE
DB 접속 정보는 INI 형태의 파일에서 읽어와서 접속하도록 하세요. 

### ISSUE THREAD

**Issue by youngjin831213** [Quad-YCDC/AlienVault-Crawler#2]
"""
[PSQL]
IPADDR = 192.168.10.10
PORT = 1111 
"""

와 같이 INI 형태의 파일을 읽어와서 DB접속을 하세요 

모든 정보는 하드코딩 하지마세요 .

**Comment by nuyh9n0j** [comment]
완료 https://github.com/Quad-YCDC/AlienVault-Crawler/commit/aa4c881eaeae4f5d7351bc5e3e990888bca28ded
